sudo: required
services:
  - docker

before_install:
  - docker build -t alp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alp/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-demo"
  env: "Docker-react-demo-env"
  bucket_name: "elasticbeanstalk-us-east-2-697551638574"
  bucket_path: "docker-react-demo"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"